function mergeToList(keys, values) {
  if (keys.length !== values.length) {
    throw new Error("Keys and values lists must have the same length.");
  }

  const resultMap = new Map();
  for (let i = 0; i < keys.length; i++) {
    resultMap.set(keys[i], values[i]);
  }
  return resultMap;
}

function printMapInFormat(map) {
  let output = "";
  map.forEach((value, key) => {
    output += `'${key}':'${value}', `;
  });
  // Remove the trailing comma and space
  if (output.length > 1) {
    output = output.slice(0, -2);
  }
  output += "";
  console.log("");
  console.log("");
  console.log("");
  console.log("");
  console.log(output);
  console.log("");
  console.log("");
  console.log("");
  console.log("");
}

const keys = [
  "WelcomeBackLoginToContinue",
  "Login",
  "Email/PhoneNumber",
  "Password",
  "OopsForgotPassword",
  "ContinueWith",
  "DontHaveAnAccount",
  "Signup",
  "PleasEnterEmail/PhoneNumber",
  "PleasEnterValidEmail/PhoneNumber",
  "PleasEnterPassword",
  "ForgotPassword",
  "WereSorryToHearYou’veForgottenYourPasswordLet’sGetYouSetUpAgain",
  "Continue",
  "ResetPassword",
  "TypeInYourNewPassword",
  "PleasConfirmPassword",
  "ConfirmPassword",
  "SignUp",
  "WelcomeToEcoCreateAnAccountToContinue",
  "Or",
  "FullName",
  "Email/PhoneNumber",
  "I’mAgreeToThe",
  "TermsOfService",
  "PrivacyPolicy",
  "CreateAccount",
  "DoYouHaveAccount?",
  "LoginFailed",
  "NoAccountFound",
  "IncorrectPhoneNumberOrPassword",
  "FirstNameIsRequired",
  "FirstName",
  "LastNameIsRequired",
  "LastName",
  "Success",
  "AccountCreatedSuccessfully",
  "Error",
  "FailedToCreateAccount",
  "WishList",
  "RecentlyViewed",
  "ClearAll",
  "RecentlyLikedItems",
  "ViewItem",
  "GoodAfternoon",
  "MarketPlace",
  "FoodDelivery",
  "Notifications",
  "Messages",
  "Basket",
  "Search",
  "MyVideos",
  "Watch",
  "NumberComments",
  "Followers",
  "UploadVideo",
  "AllVideos",
  "NotBoosted",
  "Back",
  "AdvertiseYourServiceAndProducts",
  "YourVideoWillBeProcessedBeforeBeingPostedOnOurPlatform,IfItDoesn’tMeetOurCommunityPolicyTheVideoWillBeRemoved",
  "VideoCaption(optional)",
  "UploadVideo",
  "AddADescriptionOfTheVideoOrAddContactInformationForAudiencesToGetABetterUnderstandingOfYourProductOrService",
  "YourLocation",
  "OrderNow",
  "SkipBoost",
  "BoostProduct",
  "Settings",
  "LookingForDeliveryOnly",
  "ReceiverInfo(required)",
  "DeliveryDetails",
  "UnableToPerformTheRequestedOperation",
  "NoInternetConnection",
  "PleaseCheckYourInternetConnection",
  "Oops",
  "SomethingWentWrongPleaseTryAgain",
  "Done",
  "TheOperationHasCompletedSuccessfully",
  "InvalidVerificationCode",
  "Verification",
  "EnterTheVerificationCodeSentToYourPhone",
  "VerificationCode",
  "EnterTheVerificationCode",
  "Verify",
  "OrderPlacedSuccessfully",
  "YouCanViewTheStatusOnOrderDetail",
  "OrderPlacedError",
  "PleaseTryAgain",
  "Basket",
  "Remove",
  "CheckoutDetail",
  "BasketSubtotal",
  "DeliveryFee",
  "Checkout",
  "TotalPrice",
  "BasketCheckout",
  "OrderItems",
  "Item",
  "TransactionDetails",
  "Apply",
  "PaymentStatus",
  "DeliveryFee",
  "DeliverTo",
  "Name:",
  "PhoneNo:",
  "Address:",
  "Wallet",
  "AvailableInStock",
  "Reviews",
  "ProductDescription",
  "AvailableSize&Colors",
  "YouMightAlsoLike",
  "AddToBasket",
  "PostItem",
  "More",
  "FlashDeals",
  "EndsInNumber",
  "Explore",
  "New",
  "Popular",
  "ProductAddedSuccessfully",
  "FailedToAddProduct",
  "AddNewItem",
  "SelectCategory",
  "ProductDetails",
  "ProductNameIsRequired",
  "ProductName",
  "ProductDescriptionIsRequired",
  "ProductDescription",
  "ProductPriceIsRequired",
  "Price(ETB)",
  "ProductImageOrVideo(FileSizeMustBe<5MB)",
  "ProductSize&Color",
  "SelectAvailableSizes",
  "SelectAvailableColors",
  "AvailableQuantity",
  "ProductQuantityIsRequired",
  "Quantity",
  "ProductDiscount&Coupon(Optional)",
  "ProductDiscountIsRequired",
  "Discount(%)",
  "ProductCouponIsRequired",
  "Coupon",
  "BoostProduct",
  "SkipBoost",
  "BoostYourProduct",
  "DefineTheTargetAudienceYouWantToReachWithYourBoostedVideo.SelectDemographicFactorsLikeAgeRange,Gender,Countries/Regions. YouCanAlsoTargetByInterestsOrBehaviors.",
  "DoYouWantToOptimizeForMales,FemalesOrBoth?",
  "Male",
  "Female",
  "Both",
  "AgeGroup",
  "ToHelpFocusTheReachOfThisBoost,WhatInterestAreasOrCategoriesShouldWeOptimizeFor?",
  "ContinueToPayment",
  "MyProducts",
  "All",
  "Products",
  "Sold",
  "Products",
  "MyProducts",
  "AddProduct",
  "Sold",
  "Edit",
  "BoostProduct",
  "Remove",
  "AddNewItem",
  "ProductDetails",
  "ProductName:",
  "ProductCategory:",
  "ProductDescription:",
  "ProductPrice:",
  "AvailableColors:",
  "None",
  "AvailableSizes:",
  "AvailableStock:",
  "Coupon:",
  "Discount%:",
  "AddProduct",
  "OrderDetails",
  "ShippingDetails",
  "OrderID:",
  "Orders",
  "Running(number)",
  "Delivered(number)",
  "Requested(number)",
  "DeliveryInProgress",
  "Amount(number)",
  "EditProfile",
  "PhoneNumber",
  "FullName",
  "Address",
  "MyWallet",
  "WalletBalance",
  "MilesBalance",
  "NumberMiles",
  "TransactionHistory",
  "FilterByDate",
  "RechargeWallet",
  "Notifications",
  "Today",
  "SystemNotification",
  "Edit",
  "Rating",
  "Following",
  "Followers",
  "MyProducts",
  "MyWallet",
  "Menu",
  "ChangeLanguage",
  "Settings",
  "SupportCenter",
  "Terms&Conditions",
  "Referrals",
  "Settings",
  "DefaultHomePage",
  "RideApp",
  "E-commercePage",
  "FoodDelivery",
  "ColorTheme",
  "Light",
  "Dark",
  "EnableCommunicationsChannels",
  "AccountSettings",
  "Logout",
  "DeleteAccount",
  "Home",
  "Orders",
  "Watch",
  "Me",
  "RestaurantsNearby",
  "NewOrders",
  "AddDiscount",
  "Discount",
  "Discount(Optional)",
  "AddCoupon",
  "ChooseBoostType",
  "UploadBannerImage",
  "CropBannerImage",
];

const values1 = [
  "Welcome back, login to continue",
  "Login",
  "Email/Phone Number",
  "Password",
  "Oops! Forgot Password?",
  "Continue with",
  "Don’t have an account? ",
  "Signup",
  "Pleas enter Email/Phone Number",
  "Pleas enter valid Email/PhoneNumber",
  "Pleas enter Password",
  "Forgot Password",
  "We’re sorry to hear you’ve forgotten your password, let’s get you set up again",
  "Continue",
  "Reset Password",
  "Type in your new password",
  "Pleas confirm password",
  "confirm password",
  "Sign Up",
  "Welcome to Eco, create an account to continue",
  "Or",
  "Full Name",
  "Email/Phone Number",
  "I’m agree to The",
  " Terms of Service",
  "Privacy Policy",
  "Create Account",
  "Do you have account?  ",
  "Login failed",
  "No account found",
  "Incorrect phone number or password",
  "First name is required",
  "First name",
  "Last name is required",
  "Last name",
  "Success",
  "Account created successfully",
  "Error",
  "Failed to create account",
  "Wishlist",
  "Recently viewed",
  "Clear all",
  "Recently liked tems",
  "View item",
  "Good Afternoon",
  "Market place",
  "Food delivery",
  "Notifications",
  "Messages",
  "Basket",
  "Search",
  "My videos",
  "Watch",
  "@number Comments",
  "Followers",
  "Upload video",
  "All videos",
  "Not boosted",
  "Back",
  "Advertise your service and products",
  "Your video will be processed before being posted on our platform, If it doesn’t meet our community policy the video will be removed",
  "Video caption(optional)",
  "Upload video",
  "Add a description of the video or add contact information for audiences to get a better understanding of your product or service",
  "Your location",
  "Order now",
  "Skip boost",
  "Boost product",
  "Settings",
  "Looking for delivery only",
  "Receiver info(required)",
  "Delivery details",
  "Unable to perform the requested operation",
  "No internet connection",
  "Please check your internet connection",
  "Oops",
  "Something went wrong please try again",
  "Done",
  "The operation has completed successfully",
  "Invalid verification code",
  "Verification",
  "Enter the verification code sent to your phone",
  "Verification code",
  "Enter the verification code",
  "Verify",
  "Order placed successfully",
  "You can view the status on order detail",
  "Order placed error",
  "Please try again",
  "Basket",
  "Remove",
  "Checkout detail",
  "Basket subtotal",
  "Delivery fee",
  "Checkout",
  "Total price",
  "Basket checkout",
  "Order items",
  "Item",
  "Transaction details",
  "Apply",
  "Payment status",
  "Delivery fee",
  "Deliver to",
  "Name:",
  "Phone No:",
  "Address:",
  "Wallet",
  "Available in stock",
  "Reviews",
  "Product description",
  "Available size & colors",
  "You might also like",
  "Add to basket",
  "Post item",
  "More",
  "Flash Deals",
  "Ends in 02:34:56",
  "Explore",
  "New",
  "Popular",
  "Product added successfully",
  "Failed to add product",
  "Add new item",
  "Select category",
  "Product details",
  "Product name is required",
  "Product name",
  "Product description is required",
  "Product description",
  "Product price is required",
  "Price(ETB)",
  "Product image or video(File size must be<5MB)",
  "Product size & color",
  "Select available sizes",
  "Select available colors",
  "Available quantity",
  "Product quantity is required",
  "Quantity",
  "Product discount & coupon(Optional)",
  "Product discount Is required",
  "Discount(%)",
  "Product coupon is required",
  "Coupon",
  "Boost product",
  "Skip boost",
  "Boost your product",
  "Define the target audience you want to reach with your boosted video. Select demographic factors like age range, gender, countries/regions. You can also target by interests or behaviors.",
  "Do you want to optimize for males, females or both?",
  "Male",
  "Female",
  "Both",
  "Age group",
  "To help focus the reach of this boost, What interest areas or categories should we optimize for?",
  "Continue to payment",
  "My Products",
  "All",
  "Products",
  "Sold",
  "Products",
  "My products",
  "Add product",
  "Sold",
  "Edit",
  "Boost product",
  "Remove",
  "Add new item",
  "Product details",
  "Product name:",
  "Product category:",
  "Product description:",
  "Product price:",
  "Available colors:",
  "None",
  "Available sizes:",
  "Available stock:",
  "Coupon:",
  "Discount%:",
  "Add product",
  "Order details",
  "Shipping details",
  "Order id:",
  "Orders",
  "Running(@number)",
  "Delivered(@number)",
  "Requested (@number)",
  "Delivery in progress",
  "Amount (@number)",
  "Edit profile",
  "Phone number",
  "Full name",
  "Address",
  "My wallet",
  "Wallet balance",
  "Miles balance",
  "@number miles",
  "Transaction history",
  "Filter by date",
  "Recharge wallet",
  "Notifications",
  "Today",
  "System notification",
  "Edit",
  "Rating",
  "Following",
  "Followers",
  "My products",
  "My wallet",
  "Menu",
  "Change language",
  "Settings",
  "Support center",
  "Terms & Conditions",
  "Referrals",
  "Settings",
  "Default home page",
  "Ride app",
  "E-commerce page",
  "Food delivery",
  "Color theme",
  "Light",
  "Dark",
  "Enable communications channels",
  "Account settings",
  "Logout",
  "Delete account",
  "Home",
  "Orders",
  "Watch",
  "Me",
  "Restaurants Nearby",
  "New orders",
  "Add discount",
  "Discount",
  "Discount(Optional)",
  "Add coupon",
  "Choose boost type",
  "Upload banner image",
  "Crop banner image",
];

const values2 = [
  "እንኳን ደህና መጡ፣ ለመቀጠል ይግቡ",
  "ግባ",
  "ኢሜል/ስልክ ቁጥር",
  "የይለፍ ቃል",
  "ውይ! መክፈቻ ቁልፉን ረሳኽው?",
  "በዚህ ይቀጥሉ",
  " መለያ የለህም?",
  "ተመዝገቢ",
  "እባክዎ ኢሜል/ስልክ ቁጥር ያስገቡ",
  "እባክዎ የሚሰራ ኢሜይል/ስልክ ቁጥር ያስገቡ",
  "እባክዎ የይለፍ ቃል ያስገቡ",
  "መክፈቻ ቁልፉን ረሳኽው",
  "የይለፍ ቃልህን እንደረሳህ በመስማታችን እናዝናለን፣ እንደገና እናዋቅርህ",
  "ቀጥል",
  "የይለፍ ቃል ዳግም አስጀምር",
  "አዲሱን የይለፍ ቃልዎን ያስገቡ",
  "እባክዎ የይለፍ ቃል ያረጋግጡ",
  "የይለፍ ቃል አረጋግጥ",
  "ተመዝገቢ",
  "ወደ Eco እንኳን በደህና መጡ፣ ለመቀጠል መለያ ይፍጠሩ",
  "ወይም",
  "ሙሉ ስም",
  "ኢሜል/ስልክ ቁጥር",
  "በ The ተስማምቻለሁ",
  " የአገልግሎት ውል",
  "የ ግል የሆነ",
  "መለያ ይፍጠሩ",
  " መለያ አለህ?",
  "ሎጎን ፋእለድ",
  "ምንም መለያ አልተገኘም።",
  "የተሳሳተ የስልክ ቁጥር ወይም የይለፍ ቃል",
  "የመጀመሪያ ስም ያስፈልጋል",
  "የመጀመሪያ ስም",
  "የአያት ስም ያስፈልጋል",
  "የአያት ስም",
  "ስኬት",
  "መለያ በተሳካ ሁኔታ ተፈጥሯል።",
  "ስህተት",
  "መለያ መፍጠር አልተሳካም።",
  "የምኞት ዝርዝር",
  "በቅርብ ጊዜ የታዩ",
  "ሁሉንም ያፅዱ",
  "በቅርብ ጊዜ የተወደዱ ዕቃዎች",
  "ንጥል ይመልከቱ",
  "እንደምን አረፈድክ",
  "የገበያ ቦታ",
  "የምግብ አቅርቦት",
  "ማሳወቂያዎች",
  "መልዕክቶች",
  "ቅርጫት",
  "ፈልግ",
  "የእኔ ቪዲዮዎች",
  "ይመልከቱ",
  "@number አስተያየቶች",
  "ተከታዮች",
  "ቪዲዮ ስቀል",
  "ሁሉም ቪዲዮዎች",
  "አልተጨመረም።",
  "ተመለስ",
  "የእርስዎን አገልግሎት እና ምርቶች ያስተዋውቁ",
  "ቪዲዮዎ በእኛ መድረክ ላይ ከመለጠፉ በፊት ይስተናገዳል፣የእኛን ማህበረሰብ ፖሊሲ የማያሟላ ከሆነ ቪዲዮው ይወገዳል",
  "የቪዲዮ መግለጫ (አማራጭ)",
  "ቪዲዮ ስቀል",
  "ስለምርትዎ ወይም አገልግሎትዎ የተሻለ ግንዛቤ ለማግኘት የቪዲዮውን መግለጫ ያክሉ ወይም ለተመልካቾች የእውቂያ መረጃ ያክሉ",
  "አካባቢህ",
  "አሁን እዘዝ",
  "ጭማሪን ዝለል",
  "ምርትን ያሳድጉ",
  "ቅንብሮች",
  "ማድረስ ብቻ በመፈለግ ላይ",
  "የተቀባይ መረጃ (አስፈላጊ)",
  "የማድረስ ዝርዝሮች",
  "የተጠየቀውን ተግባር ማከናወን አልተቻለም",
  "ምንም የበይነመረብ ግንኙነት የለም።",
  "እባክዎ የበይነመረብ ግንኙነትዎን ያረጋግጡ",
  "ውይ",
  "የሆነ ችግር ተፈጥሯል እባክዎ እንደገና ይሞክሩ",
  "ተከናውኗል",
  "ክዋኔው በተሳካ ሁኔታ ተጠናቋል",
  "ልክ ያልሆነ የማረጋገጫ ኮድ",
  "ማረጋገጥ",
  "ወደ ስልክዎ የተላከውን የማረጋገጫ ኮድ ያስገቡ",
  "የማረጋገጫ የሚስጥር ቁጥር",
  "የማረጋገጫ ኮዱን ያስገቡ",
  "አረጋግጥ",
  "ትዕዛዝ በተሳካ ሁኔታ ቀርቧል",
  "ሁኔታውን በትዕዛዝ ዝርዝር ውስጥ ማየት ይችላሉ።",
  "የትእዛዝ ስህተት",
  "እባክዎ ዳግም ይሞክሩ",
  "ቅርጫት",
  "አስወግድ",
  "ዝርዝር ይመልከቱ",
  "የቅርጫት ንዑስ ድምር",
  "የማስረከቢያ ክፍያ",
  "ጨርሰህ ውጣ",
  "ጠቅላላ ዋጋ",
  "የቅርጫት ማረጋገጫ",
  "እቃዎችን ይዘዙ",
  "ንጥል",
  "የግብይት ዝርዝሮች",
  "ያመልክቱ",
  "የክፍያ ሁኔታ",
  "የማስረከቢያ ክፍያ",
  "ማድረስ ለ",
  "ስም፡",
  "ስልክ ቁጥር:",
  "አድራሻ፡-",
  "የኪስ ቦርሳ",
  "በክምችት ውስጥ ይገኛል።",
  "ግምገማዎች",
  "የምርት ማብራሪያ",
  "የሚገኝ መጠን እና ቀለሞች",
  "እርስዎም ሊወዱት ይችላሉ።",
  "ቅርጫቱ ውስጥ ይጨምሩ",
  "ንጥል ይለጥፉ",
  "ተጨማሪ",
  "የፍላሽ ቅናሾች",
  "በ02፡34፡56 ያበቃል",
  "ያስሱ",
  "አዲስ",
  "ታዋቂ",
  "ምርቱ በተሳካ ሁኔታ ታክሏል።",
  "ምርት ማከል አልተሳካም።",
  "አዲስ ንጥል ያክሉ",
  "ምድብ ይምረጡ",
  "የምርት ዝርዝሮች",
  "የምርት ስም ያስፈልጋል",
  "የምርት ስም",
  "የምርት መግለጫ ያስፈልጋል",
  "የምርት ማብራሪያ",
  "የምርት ዋጋ ያስፈልጋል",
  "ዋጋ(ETB)",
  "የምርት ምስል ወይም ቪዲዮ(የፋይል መጠን <5MB መሆን አለበት)",
  "የምርት መጠን እና ቀለም",
  "ያሉትን መጠኖች ይምረጡ",
  "ያሉትን ቀለሞች ይምረጡ",
  "የሚገኝ መጠን",
  "የምርት መጠን ያስፈልጋል",
  "ብዛት",
  "የምርት ቅናሽ እና ኩፖን (አማራጭ)",
  "የምርት ቅናሽ ያስፈልጋል",
  "ቅናሽ(%)",
  "የምርት ኩፖን ያስፈልጋል",
  "ኩፖን",
  "ምርትን ያሳድጉ",
  "ጭማሪን ዝለል",
  "ምርትዎን ያሳድጉ",
  "በተሻሻለ ቪዲዮዎ ሊደርሱበት የሚፈልጉትን ዒላማ ታዳሚ ይግለጹ። እንደ የዕድሜ ክልል፣ ጾታ፣ አገሮች/ክልሎች ያሉ የስነ ሕዝብ አወቃቀር ሁኔታዎችን ይምረጡ። እንዲሁም በፍላጎቶች ወይም ባህሪያት ማነጣጠር ይችላሉ.",
  "ለወንዶች, ለሴቶች ወይም ለሁለቱም ማመቻቸት ይፈልጋሉ?",
  "ወንድ",
  "ሴት",
  "ሁለቱም",
  "እድሜ ክልል",
  "የዚህ ማበልጸጊያ ተደራሽነት ላይ እንዲያተኩር ለማገዝ ለየትኞቹ የፍላጎት ቦታዎች ወይም ምድቦች ማመቻቸት አለብን?",
  "መክፈሉን ይቀጥሉ",
  "የእኔ ምርቶች",
  "ሁሉም",
  "ምርቶች",
  "የተሸጠ",
  "ምርቶች",
  "የእኔ ምርቶች",
  "ምርት ይጨምሩ",
  "የተሸጠ",
  "አርትዕ",
  "ምርትን ያሳድጉ",
  "አስወግድ",
  "አዲስ ንጥል ያክሉ",
  "የምርት ዝርዝሮች",
  "የምርት ስም:",
  "የምርት ምድብ፡-",
  "የምርት ማብራሪያ:",
  "የምርት ዋጋ፡-",
  "የሚገኙ ቀለሞች:",
  "ምንም",
  "የሚገኙ መጠኖች:",
  "የሚገኝ ክምችት፡",
  "ኩፖን:",
  "ቅናሽ%፡",
  "ምርት ይጨምሩ",
  "የትዕዛዝ ዝርዝሮች",
  "የማጓጓዣ ዝርዝሮች",
  "የትዕዛዝ መታወቂያ፡-",
  "ትዕዛዞች",
  "መሮጥ (@number)",
  "ደርሷል (@number)",
  "የተጠየቀ (@number)",
  "ማድረስ በሂደት ላይ ነው።",
  "መጠን (@number)",
  "መገለጫ አርትዕ",
  "ስልክ ቁጥር",
  "ሙሉ ስም",
  "አድራሻ",
  "የኪስ ቦርሳዬ",
  "የኪስ ቦርሳ ቀሪ ሂሳብ",
  "ማይል ሚዛን",
  "@number ማይል",
  "የግብይት ታሪክ",
  "በቀን አጣራ",
  "የኪስ ቦርሳ መሙላት",
  "ማሳወቂያዎች",
  "ዛሬ",
  "የስርዓት ማሳወቂያ",
  "አርትዕ",
  "ደረጃ መስጠት",
  "በመከተል ላይ",
  "ተከታዮች",
  "የእኔ ምርቶች",
  "የኪስ ቦርሳዬ",
  "ምናሌ",
  "ቋንቋ ቀይር",
  "ቅንብሮች",
  "የድጋፍ ማዕከል",
  "ውሎች እና ሁኔታዎች",
  "ማጣቀሻዎች",
  "ቅንብሮች",
  "ነባሪ መነሻ ገጽ",
  "መተግበሪያ ያሽከርክሩ",
  "የኢ-ኮሜርስ ገጽ",
  "የምግብ አቅርቦት",
  "የቀለም ገጽታ",
  "ብርሃን",
  "ጨለማ",
  "የመገናኛ ጣቢያዎችን አንቃ",
  "መለያ ማደራጃ",
  "ውጣ",
  "መለያ ሰርዝ",
  "ቤት",
  "ትዕዛዞች",
  "ይመልከቱ",
  "እኔ",
  "በአቅራቢያ ያሉ ምግብ ቤቶች",
  "አዲስ ትዕዛዞች",
  "ቅናሽ ይጨምሩ",
  "ቅናሽ",
  "ቅናሽ (አማራጭ)",
  "ኩፖን አክል",
  "የማሳደጊያ ዓይነት ይምረጡ",
  "የባነር ምስል ስቀል",
  "የባነር ምስል ይከርክሙ",
];

const values3 = [
  "እንቋዕ ብደሓን መጻእኩም፡ ንምቕጻል እቶ",
  "መእተዊ",
  "ቁጽሪ ኢመይል/ተሌፎን።",
  "መሕለፊ ቓል",
  "እዋእ! Password ረሲዕካዮ?",
  "ብቐጽል",
  " ኣካውንት የብልካን?",
  "ምዝገባ",
  "በጃኹም ኢመይል/ቁጽሪ ተሌፎን ኣእትዉ",
  "ቅኑዕ ኢመይል/ቁጽሪ ስልኪ ኣእትዉ",
  "በጃኹም Password ኣእትዉ",
  "Password ረሲዐዮ",
  "ፓስዎርድካ ረሲዕካ ክትሰምዕ ከለና ይቕሬታ፡ እንደገና ነዳልወካ",
  "ቀፃሊ",
  "ፓስዎርድ ዳግማይ ምትካል",
  "ሓድሽ ፓስዎርድካ ጽሓፍ",
  "በጃኹም ፓስዎርድ ኣረጋግጹ",
  "ምልክት ቃል ምርግጋጽ",
  "ተመዝገብ",
  "እንቋዕ ናብ ኢኮ ብደሓን መጻእኩም፡ ንኽትቅጽል ኣካውንት ፍጠሩ",
  "ወይ",
  "ምሉእ ስም",
  "ቁጽሪ ኢመይል/ተሌፎን።",
  "ኣነ ምስ The ይሰማማዕ እየ",
  " ውዕል ኣገልግሎት",
  "ፖሊሲ ውልቃዊ ሓበሬታ",
  "ኣካውንት ምፍጣር",
  " ኣካውንት ኣለካ ድዩ?",
  "ምእታው ኣይተዓወተን",
  "ዝኾነ ኣካውንት ኣይተረኽበን።",
  "ጌጋ ቁጽሪ ተሌፎን ወይ ፓስዎርድ",
  "ቀዳማይ ስም የድሊ",
  "ናይ መጀመርታ ሽም",
  "መወዳእታ ስም የድሊ",
  "ናይ መወዳእታ ሽም",
  "ዓወት",
  "ኣካውንት ብዓወት ተፈጢሩ",
  "ስሕተት",
  "ኣካውንት ምፍጣር ኣይከኣለን",
  "ዝርዝር ድሌታት",
  "ኣብ ቀረባ እዋን ዝተራእየ",
  "ኩሉ ኣጽርዮ",
  "ኣብ ቀረባ እዋን ዝፈተኹዎ tems",
  "ኣቕሓ ርአ",
  "ከመይ ውዒሎም",
  "ዕዳጋ ቦታ",
  "ኣወሃህባ መግቢ",
  "መፍለጢታት",
  "መልእኽትታት",
  "መሶብ",
  "ምድላይ",
  "ቪድዮታተይ",
  "ተመልከት",
  "@number ርእይቶታት",
  "ተኸታተልቲ",
  "ቪድዮ ስቐል",
  "ኩሉ ቪድዮታት",
  "ኣይተደፋፍአን",
  "ዝባን",
  "ኣገልግሎትካን ፍርያትካን ኣወዓውዕ",
  "ቪድዮኹም ቅድሚ ኣብ መድረኽና ምልጣፉ ክስርሓሉ እዩ፣ ንማሕበረሰባዊ ፖሊሲና እንተዘይተማሊኡ እቲ ቪድዮ ክእለ እዩ።",
  "ቪድዮ መግለጺ(ኣማራጺ)",
  "ቪድዮ ስቐል",
  "መግለጺ ናይቲ ቪድዮ ወስኸሉ ወይ ንሰማዕቲ ብዛዕባ ፍርያትካ ወይ ኣገልግሎትካ ዝሓሸ ርድኢት ንምርካብ ናይ ርክብ ሓበሬታ ወስኸሉ።",
  "ኣቀማምጣኻ",
  "ሕጂ ኣዘዙ",
  "ስኪፕ ቡስት",
  "ፍርያት ምዕባይ",
  "ቅጥዕታት",
  "ንመብጽሒ ጥራይ ትደሊ",
  "ናይ ተቐባሊ ሓበሬታ(ኣድላዪ)",
  "ዝርዝር ኣወሃህባ",
  "እቲ ዝተሓተተ ስርሒት ክፍጽም ኣይከኣለን",
  "ናይ ኢንተርነት ምትእስሳር የለን",
  "በጃኹም ምትእስሳር ኢንተርነትኩም ኣረጋግጹ",
  "እዋእ",
  "ገለ ተጋግዩ በጃኹም ደጊምኩም ፈትኑ",
  "ምውዳእ",
  "እቲ ስርሒት ብዓወት ተዛዚሙ ኣሎ።",
  "ዘይሕጋዊ ናይ ምርግጋጽ ኮድ",
  "ምርግጋጽ",
  "ናብ ስልክኻ ዝተላእከ ናይ ምርግጋጽ ኮድ ኣእቱ",
  "ናይ ምርግጋጽ ኮድ",
  "ናይ ምርግጋጽ ኮድ ኣእትዉ",
  "ኣረጋግጽ",
  "ትእዛዝ ብዓወት ተዋሂቡ።",
  "እቲ ኩነታት ኣብ ዝርዝር ትእዛዝ ክትዕዘቡ ትኽእሉ ኢኹም።",
  "ትእዛዝ ዝተቐመጠ ጌጋ",
  "በጃኹም ደጊምኩም ፈትኑ",
  "መሶብ",
  "ኣወግድ",
  "ዝርዝር ምውጻእ ገንዘብ",
  "መሶብ ንኡስ ድምር",
  "ናይ ምብጻሕ ክፍሊት",
  "ምውጻእ ገንዘብ",
  "ጠቕላላ ዋጋ",
  "መሶብ ምውጻእ ገንዘብ",
  "ንብረት ምእዛዝ",
  "ኣቕሓ",
  "ዝርዝር ትራንዛክሽን",
  "ኣተግብር",
  "ኩነታት ክፍሊት",
  "ናይ ምብጻሕ ክፍሊት",
  "ናብ ምብጻሕ",
  "ሽም:",
  "ቁጽሪ ስልኪ፤",
  "አድራሻ:",
  "ሳንጣ",
  "ኣብ ስቶክ ኣሎ።",
  "ሪኢቶታት",
  "መግለጺ ፍርያት",
  "ዝርከብ ዓቐን & ሕብርታት",
  "ክትፈትውዎ እውን ትኽእሉ ኢኹም።",
  "ኣብ መሶብ ወስኹሉ።",
  "ፖስት ዝብል ኣቕሓ",
  "ቡዙሕ",
  "ፍላሽ ዲልስ",
  "ኣብ 02፡34፡56 ይዛዘም",
  "ዳህሰሳ",
  "ሓድሽ",
  "ህቡብ",
  "ፍርያት ብዓወት ተወሰኸ",
  "ፍርያት ምውሳኽ ኣይከኣለን",
  "ሓድሽ ኣቕሓ ምውሳኽ",
  "ምድብ ምረጽ",
  "ዝርዝር ፍርያት",
  "ስም ፍርያት የድሊ",
  "ስም ፍርያት",
  "መግለጺ ፍርያት የድሊ",
  "መግለጺ ፍርያት",
  "ዋጋ ፍርያት የድሊ",
  "ዋጋ(ETB)",
  "ምስሊ ፍርያት ወይ ቪድዮ(ዓቐን ፋይል<5MB ክኸውን ኣለዎ)",
  "መጠን ፍርያት & ሕብሪ",
  "ዝርከቡ ዓቐናት ምረጽ",
  "ዝርከቡ ሕብርታት ምረጽ",
  "ዝርከብ ብዝሒ",
  "ብዝሒ ፍርያት የድሊ",
  "መጠን",
  "ቅናሽ ፍርያት & ኩፖን(ኣማራጺ)",
  "ቅናሽ ፍርያት የድሊ",
  "ዘይቑጸር(%)",
  "ናይ ፍርያት ኩፖን የድሊ",
  "ኩፖን እዩ።",
  "ፍርያት ምዕባይ",
  "ስኪፕ ቡስት",
  "ፍርያትካ ኣዕብዮ",
  "በቲ ዝተዓጻጸፈ ቪድዮኻ ክትበጽሖ እትደሊ ዕላማ ተዓዘብቲ ግለጽ። ዲሞግራፊካዊ ረቛሒታት ከም ዕድመ ደረጃ፣ ጾታ፣ ሃገራት/ዞባታት ምረጽ። ብተገዳስነት ወይ ብባህርያት እውን ዕላማ ክትገብር ትኽእል ኢኻ።",
  "ንደቂ ተባዕትዮ፡ ንደቂ ኣንስትዮ ወይ ንኽልቲኦም ክትጥዕም ትደሊ ዲኻ?",
  "ተባዕታይ",
  "ኣንስተይቲ",
  "ክልቲኡ",
  "ጕጅለ ዕድመ",
  "ንዝርገሐ ናይዚ ምዕባይ ንምትኳር ንምሕጋዝ፡ ኣየኖት ናይ ተገዳስነት መዳያት ወይ ምድባት ክንጥዕሞም ይግባእ?",
  "ናብ ክፍሊት ቀጽል",
  "ፍርያተይ",
  "ኩሎም",
  "ፍርያት",
  "ሽዩጥ",
  "ፍርያት",
  "ፍርያተይ",
  "ፍርያት ምውሳኽ",
  "ሽዩጥ",
  "ምዕራይ",
  "ፍርያት ምዕባይ",
  "ኣወግድ",
  "ሓድሽ ኣቕሓ ምውሳኽ",
  "ዝርዝር ፍርያት",
  "ስም ፍርያት፤",
  "ምድብ ፍርያት፤",
  "መግለጺ ፍርያት፤",
  "ዋጋ ፍርያት፤",
  "ዝርከቡ ሕብርታት፤",
  "ዋላ ሓደ",
  "ዝርከቡ ዓቐናት፤",
  "ኣብ ዝርከብ ስቶክ፤",
  "ኩፖን፤",
  "ዘይቑጸር%:",
  "ፍርያት ምውሳኽ",
  "ዝርዝር ትእዛዝ",
  "ዝርዝር ምልኣኽ",
  "ትእዛዝ id:",
  "ትእዛዛት።",
  "ምጉያይ(@number)",
  "ተረኺቡ(@number)",
  "ዝተሓተተ (@number)",
  "ኣወሃህባ ኣብ ምክያድ ይርከብ።",
  "መጠን ገንዘብ (@number)",
  "ፕሮፋይል ኣርትዕ",
  "ቁጽሪ ተሌፎን።",
  "ምሉእ ስም",
  "አድራሻ",
  "ቦርሳይ",
  "ሚዛን ቦርሳ",
  "ማይልስ ሚዛን።",
  "@number ማይልስ",
  "ታሪኽ ትራንዛክሽን",
  "ብዕለት ኣጽርዮ",
  "ሪቻርጅ ቦርሳ",
  "መፍለጢታት",
  "ሎምዓንቲ",
  "ናይ ስርዓት መፍለጢ",
  "ምዕራይ",
  "ደረጃ ምሃብ",
  "ምኽታል",
  "ተኸታተልቲ",
  "ፍርያተይ",
  "ቦርሳይ",
  "ዝርዝር መግቢ",
  "ቋንቋ ምቕያር",
  "ቅጥዕታት",
  "ማእከል ደገፍ",
  "ውዕላትን ቅጥዕታትን",
  "ሪፈራል ምግባር",
  "ቅጥዕታት",
  "ነባሪ መበገሲ ገጽ",
  "ራይድ ኣፕ",
  "ናይ ኢ-ኮሜርስ ገጽ",
  "ኣወሃህባ መግቢ",
  "ሕብራዊ ቴማ",
  "ብርሃን",
  "ፀልማት",
  "ናይ ርክብ መስመራት ምኽኣል",
  "ቅጥዕታት ኣካውንት።",
  "ኣውት ኣውት",
  "ኣካውንት ምድምሳስ",
  "ገዛ",
  "ትእዛዛት።",
  "ተመልከት",
  "ኣነ",
  "ኣብ ቀረባ ዝርከቡ ቤት መግቢ",
  "ሓድሽ ትእዛዛት።",
  "ቅናሽ ወስኹሉ።",
  "ዘይቑጸር",
  "ቅናሽ(ኣማራፂ)",
  "ኩፖን ወስኹሉ።",
  "ዓይነት ምዕባይ ምረጽ",
  "ምስሊ ባነር ስቐል",
  "ስእሊ ባነር ምቑራጽ",
];

const values4 = [
  "Baga nagaan dhuftan, itti fufuuf seenaa",
  "Galmaa'i",
  "Lakkoofsa Imeelii/Bilbilaa",
  "Jecha iccitii",
  "Oops! Password dagattaniittuu?",
  "Itti fufaa",
  " Akkaawuntii hin qabduu?",
  "Galmaa'i",
  "Maaloo Email/Lakkoofsa Bilbilaa galchaa",
  "Maaloo Email/PhoneNumber sirrii ta'e galchi",
  "Maaloo Password galchaa",
  "Password dagadheera",
  "Jecha icciitii dagachuu keessan dhaga'uu keenyatti gadda, ammas isin haa qopheessinu",
  "Itti fufuu",
  "Jecha Darbii Irra Deebi'i",
  "Jecha icciitii haaraa kee barreessi",
  "Maaloo jecha icciitii mirkaneessaa",
  "jecha icciitii mirkaneessuu",
  "Galmaa'i",
  "Baga gara Eco dhuftan, itti fufuuf account uumuu",
  "Yookaan",
  "Maqaa Guutuu",
  "Lakkoofsa Imeelii/Bilbilaa",
  "Ani walii gala The",
  " Haala Tajaajilaa",
  "Imaammata Dhuunfaa",
  "Herrega Uumuu",
  " Account qabduu?",
  "Galmeen hin milkoofne",
  "Akkaawuntii hin argamne",
  "Lakkoofsa bilbilaa ykn jecha icciitii sirrii hin taane",
  "Maqaa jalqabaa barbaachisa",
  "Maqaa jalqabaa",
  "Maqaan dhumaa barbaachisaadha",
  "Maqaa akaakayyuu",
  "Milkaa'ina",
  "Account milkaa'inaan uumame",
  "Dogoggora",
  "Akkaawuntii uumuu hin dandeenye",
  "Tarree hawwii",
  "Dhiheenya kana ilaalame",
  "Hundaa qulqulleessi",
  "Dhiheenya kana like tems",
  "Wanticha ilaali",
  "Akkam ooltan",
  "Bakka gabaa",
  "Nyaata geessuu",
  "Beeksisa",
  "Ergaawwan",
  "Basket jedhamu",
  "Barbaaduu",
  "Viidiyoowwan koo",
  "Ilaaluu",
  "@number Yaada",
  "Hordoftoota",
  "Viidiyoo ol kaa'aa",
  "Viidiyoo hunda",
  "Boosted miti",
  "Dugda",
  "Tajaajila fi oomisha keessan beeksisa",
  "Viidiyoon keessan waltajjii keenya irratti osoo hin maxxanfamin dura ni hojjetama, Yoo imaammata hawaasa keenyaa hin guunne viidiyoon sun ni haqama",
  "Mata duree viidiyoo(dirqama) .",
  "Viidiyoo ol kaa'aa",
  "Ibsa viidiyoo sanaa itti dabali ykn odeeffannoo quunnamtii dhaggeeffattoonni itti dabali, oomisha ykn tajaajila kee irratti hubannoo gaarii akka qabaataniif",
  "Bakki ati jirtu",
  "Amma ajajaa",
  "Boost darbuu",
  "Boost oomisha",
  "Sajoo",
  "Geejjibaa qofa barbaada",
  "Odeeffannoo fudhataa(barbaachisaa)",
  "Bal'ina geejjibaa",
  "Hojii gaafatame raawwachuu hin dandeenye",
  "Intarneetii hin qabu",
  "Mee interneetii keessan ilaalaa",
  "Oops",
  "Wanti tokko dogoggora ta'e mee irra deebi'aa yaalaa",
  "Raawwatame",
  "Opireeshiniin kun milkaa'inaan xumurameera",
  "Koodii mirkaneessaa sirrii hin taane",
  "Mirkaneessuu",
  "Koodii mirkaneessaa bilbila keessanitti ergame galchaa",
  "Koodii mirkaneessuu",
  "Koodii mirkaneessuu galchi",
  "Dhugoomsuu",
  "Ajajni milkaa'inaan kenname",
  "Haala ajaja irratti bal'inaan ilaaluu dandeessu",
  "Dogoggora tartiiba kaa'ame",
  "Mee irra deebi'ii yaalaa",
  "Basket jedhamu",
  "Irraa kaasuu",
  "Bal'inaan ilaalaa",
  "Waliigala xiqqaa basket",
  "Kaffaltii geejjibaa",
  "Checkout",
  "Gatii waliigalaa",
  "Basket checkout gochuu",
  "Meeshaalee ajajuu",
  "Wanta",
  "Bal’ina daldalaa",
  "Hojiirra oolchuu",
  "Haala kaffaltii",
  "Kaffaltii geejjibaa",
  "Gara geessuu",
  "Maqaa:",
  "Lakk Bilbilaa:",
  "Teessoo:",
  "Boorsaa xiqqoo",
  "Stock keessatti argama",
  "Irra deebiin",
  "Ibsa oomishaa",
  "Saayizii & halluuwwan jiran",
  "Akkasumas jaallachuu dandeessa",
  "Gara basket tti dabali",
  "Meeshaa maxxansaa",
  "Caalaa",
  "Waliigaltee Flash",
  "Sa'aatii 02:34:56tti xumurama",
  "Gadi fageenyaan ibsuu",
  "Haaraa",
  "Beekamaa",
  "Omishni milkaa'inaan dabalameera",
  "Omisha dabaluu hin dandeenye",
  "Wanti haaraa itti dabali",
  "Ramaddii filadhu",
  "Bal'ina oomishaa",
  "Maqaan oomishaa barbaachisaadha",
  "Maqaa oomishaa",
  "Ibsi oomishaa barbaachisaadha",
  "Ibsa oomishaa",
  "Gatiin oomishaa barbaachisaadha",
  "Gatii(ETB)",
  "Fakkii ykn viidiyoo oomishaa(File size<5MB ta'uu qaba)",
  "Guddina oomishaa & halluu",
  "Safarawwan jiran filadhu",
  "Halluuwwan jiran filadhu",
  "Baay’ina argamu",
  "Baay’inni oomishaa barbaachisaadha",
  "Baay'ina",
  "Hir'ina oomishaa & kuuppani(Filannoo)",
  "Hir'inni oomishaa Ni barbaachisa",
  "Gatii gadi bu'aa(%)",
  "Kuuppoonii oomishaa barbaachisa",
  "Kuuppoonii",
  "Boost oomisha",
  "Boost darbuu",
  "Omisha keessan guddifadhaa",
  "Viidiyoo boosted keetiin target audience bira gahuu barbaaddu ibsi. Qabxiilee dimogiraafii kan akka umurii, saala, biyyoota/naannoo filadhu. Fedhii ykn amala irrattis xiyyeeffachuu dandeessa.",
  "Dhiira, dubara ykn lamaan isaaniif optimize gochuu barbaadduu?",
  "Dhiira",
  "Dhalaa",
  "Lachuu",
  "Garee umurii",
  "Dhaqqabummaa jajjabina kanaa irratti xiyyeeffachuuf gargaaruuf, Naannoowwan fedhii ykn gosoota maalif optimize gochuu qabna?",
  "Kaffaltii itti fufaa",
  "Oomishaalee Koo",
  "Hunda",
  "Oomishaalee",
  "Gurgure",
  "Oomishaalee",
  "Oomishaalee koo",
  "Omisha itti dabali",
  "Gurgure",
  "Gulaaluu",
  "Boost oomisha",
  "Irraa kaasuu",
  "Wanti haaraa itti dabali",
  "Bal'ina oomishaa",
  "Maqaa oomishaa:",
  "Ramaddii oomishaa:",
  "Ibsa oomishaa:",
  "Gatiin oomishaa: 1.1.",
  "Halluuwwan jiran:",
  "Homaa",
  "Saayiziiwwan jiran:",
  "Istookii jiru:",
  "Kuuppoonii: 1.1.",
  "Gatii gadi bu'aa%:",
  "Omisha itti dabali",
  "Bal'ina ajaja",
  "Bal'ina ergaa",
  "Id ajaja:",
  "Ajaja",
  "Fiigicha(@number) .",
  "Kan geessise(@number) .",
  "Gaafatame (@number) .",
  "Geejjibni adeemsa irra jira",
  "Maallaqa (@number) .",
  "Profaayilii gulaali",
  "Lakkoofsa bilbilaa",
  "Maqaa guutuu",
  "Teessoo",
  "Borsaa koo",
  "Hafnaan boorsaa",
  "Madaallii maayilii",
  "@number maayilii",
  "Seenaa daldalaa",
  "Guyyaadhaan calaluu",
  "Borsaa irra deebi'ii chaarjii",
  "Beeksisa",
  "Har'a",
  "Beeksisa sirnaa",
  "Gulaaluu",
  "Sadarkaa kennuu",
  "Hordofuu",
  "Hordoftoota",
  "Oomishaalee koo",
  "Borsaa koo",
  "Menu",
  "Afaan jijjiiri",
  "Sajoo",
  "Giddugala deeggarsa",
  "Haalawwanii fi Dambiiwwan",
  "Rifaralaa",
  "Sajoo",
  "Fuula jalqabaa durtii",
  "Appii yaabbachuu",
  "Fuula daldala elektirooniksii",
  "Nyaata geessuu",
  "Mata duree halluu",
  "Ifa",
  "Duukkana",
  "Karaalee qunnamtii dandeessisi",
  "Sajoo herregaa",
  "Ba'i",
  "Akkaawuntii haquu",
  "Mana",
  "Ajaja",
  "Ilaaluu",
  "Ana",
  "Manneen Nyaataa Dhihoo",
  "Ajaja haaraa",
  "Hir'ina itti dabali",
  "Gatii gadi bu'aa",
  "Hir'ina(Filannoo) .",
  "Kuuppoonii itti dabali",
  "Gosa boost filadhu",
  "Fakkii banner olkaa'aa",
  "Fakkii banner muraa",
];

const values5 = [
  "Soo dhawoow, soo gal si aad u sii wadato",
  "Soo gal",
  "Iimayl/Lambarka Taleefanka",
  "Furaha",
  "Haah! Ma ilowday Password-ka",
  "Ku sii wad",
  " Xisaab ma lihid?",
  "Isdiiwaangali",
  "Fadlan geli Email/Lambarka Telefoonka",
  "Fadlan gali iimayl/lambar taleefoon sax ah",
  "Fadlan geli erayga sirta ah",
  "Furaha la ilaaway",
  "Waan ka xunnahay inaan maqalno inaad illowday eraygaaga sirta ah, aan mar kale kugu diyaarinno",
  "Sii wad",
  "Dib u deji erayga sirta ah",
  "Ku qor furahaaga cusub",
  "Fadlan xaqiiji erayga sirta ah",
  "Xaqiiji erayga sirta ah",
  "Isdiiwaangeli",
  "Ku soo dhawoow Eco, samee akoon si aad u sii wadato",
  "Ama",
  "Magaca oo buuxa",
  "Iimayl/Lambarka Taleefanka",
  "Waan ogolahay The",
  " Shuruudaha Adeegga",
  "Qaanuunka Arrimaha Khaaska ah",
  "Abuur Account",
  " Ma leedahay xisaab?",
  "Gelitaanku wuu fashilmay",
  "Xisaab lama helin",
  "Lambarka taleefanka ama erayga sirta ah ee khaldan",
  "Magaca koowaad ayaa loo baahan yahay",
  "Magaca hore",
  "Magaca dambe ayaa loo baahan yahay",
  "Magaca dambe",
  "Guul",
  "Akoonka si guul leh ayaa loo sameeyay",
  "Khalad",
  "Ku guuldareystay in la abuuro akoon",
  "Liiska rajada",
  "Dhawaan la arkay",
  "Nadiifi dhammaan",
  "Walaxda dhawaan la jeclaaday",
  "Eeg shayga",
  "Galab wanaagsan",
  "Goobta suuqa",
  "gaarsiin cunto",
  "Ogeysiisyada",
  "Fariimaha",
  "Basket",
  "Raadi",
  "Muuqaaladeyda",
  "Daawo",
  "@number Faallo",
  "raacayaal",
  "Soo rar muqaal",
  "Dhammaan fiidiyowyada",
  "Lama kicin",
  "Dib u noqo",
  "Xayeysii adeegaaga iyo alaabtaada",
  "Fiidiyowgaaga waa la habayn doonaa ka hor inta aan lagu dhejin barxaddayada, Haddii aanu waafaqsanayn siyaasaddayada bulshada fiidyaha waa laga saari doonaa",
  "Qoraal fiidiyoow ah (ikhtiyaar)",
  "Soo rar muqaal",
  "Ku dar sharaxaad fiidyowga ama ku dar macluumaadka xidhiidhka ee dhagaystayaashu si ay u helaan faham wanaagsan oo ku saabsan alaabtaada ama adeeggaaga",
  "Goobtaada",
  "Dalbo hadda",
  "Ka bood kobcinta",
  "Kobcinta alaabta",
  "Dejinta",
  "Raadinta dhalmada kaliya",
  "Macluumaadka qaataha (loo baahan yahay)",
  "Faahfaahinta gaarsiinta",
  "Aan awoodin in uu fuliyo hawlgalka la codsaday",
  "Ma jiro xiriir internet",
  "Fadlan hubi xidhiidhkaaga intarneedka",
  "Hooy",
  "Wax baa khaldamay fadlan isku day markale",
  "La sameeyay",
  "Hawlgalku wuxuu ku dhamaaday si guul ah",
  "Koodhka xaqiijinta ee aan ansax ahayn",
  "Xaqiijinta",
  "Geli lambarka xaqiijinta ee loo soo diray taleefankaaga",
  "Koodhka xaqiijinta",
  "Geli lambarka xaqiijinta",
  "Xaqiiji",
  "Dalabka si guul leh ayaa loo dhigay",
  "Waxaad ka eegi kartaa heerka faahfaahinta dalabka",
  "Dalabka la dhigay qalad",
  "Fadlan isku day mar kale",
  "Basket",
  "Ka saar",
  "Faahfaahinta hubin",
  "Wadarta guud ee dambiisha",
  "Kharashka keenista",
  "Baadhid",
  "Wadarta qiimaha",
  "Hubinta kolayga",
  "Dalbo alaabta",
  "Shayga",
  "Faahfaahinta wax kala iibsiga",
  "Codso",
  "Heerka lacag bixinta",
  "Kharashka keenista",
  "Gaarsii",
  "Magaca:",
  "Lambarka Taleefanka:",
  "Cinwaanka:",
  "Wallet",
  "Lagu heli karo kaydka",
  "Faallooyin",
  "Sharaxaada badeecada",
  "Cabbirka iyo midabada la heli karo",
  "Waxa kale oo aad jeclaan kartaa",
  "Ku dar dambiisha",
  "Shayga ku dheji",
  "Wax badan",
  "Heshiisyada Flash",
  "Wuxuu dhamaanayaa 02:34:56",
  "Baadh",
  "Cusub",
  "caanka ah",
  "Alaabta lagu daray si guul leh",
  "Ku guuldareystay in lagu daro alaabta",
  "Ku dar shay cusub",
  "Dooro qaybta",
  "Faahfaahinta alaabta",
  "Magaca alaabta ayaa loo baahan yahay",
  "Magaca alaabta",
  "Sharaxaada badeecada ayaa loo baahan yahay",
  "Sharaxaada badeecada",
  "Qiimaha alaabta ayaa loo baahan yahay",
  "Qiimaha (ETB)",
  "Sawirka badeecada ama fiidyaha (cabbirka faylka waa inuu noqdaa <5MB)",
  "Cabbirka badeecada & midabka",
  "Dooro cabbirrada la heli karo",
  "Dooro midabada la heli karo",
  "Tirada la heli karo",
  "Tirada alaabta ayaa loo baahan yahay",
  "Tirada",
  "Qiimo dhimista alaabta & kuuban (Ikhtiyaar)",
  "Dhimista alaabta ayaa loo baahan yahay",
  "Qiimo dhimis(%)",
  "Kuubboon alaabta ayaa loo baahan yahay",
  "Kuuban",
  "Kobcinta alaabta",
  "Ka bood kobcinta",
  "Kordhi alaabtaada",
  "Qeex dhagaystayaasha bartilmaameedka ah ee aad rabto inaad ku gaadho fiidyahaaga la xoojiyay. Dooro arrimaha tirakoobka sida da'da, jinsiga, wadamada/gobolada. Waxaad sidoo kale bartilmaameedsan kartaa danaha ama dabeecadaha.",
  "Ma rabtaa in aad u wanaajiso ragga, dheddigga ama labadaba?",
  "Lab",
  "Dheddig",
  "Labadaba",
  "Kooxda da'da",
  "Si loo caawiyo in diiradda la saaro gaaritaanka kor u qaadistan, Waa maxay meelaha xiisaha ama qaybaha ay tahay in aan u wanaajino?",
  "Sii wad bixinta",
  "Alaabtayda",
  "Dhammaan",
  "Alaabta",
  "La iibiyay",
  "Alaabta",
  "Alaabtayda",
  "Ku dar badeecada",
  "La iibiyay",
  "Wax ka beddel",
  "Kobcinta alaabta",
  "Ka saar",
  "Ku dar shay cusub",
  "Faahfaahinta alaabta",
  "Magaca alaabta:",
  "Qaybta alaabta:",
  "Sharaxaada badeecada:",
  "Qiimaha alaabta:",
  "Midabada la heli karo:",
  "Midna",
  "Cabbirrada la heli karo:",
  "Kaydka la heli karo:",
  "Kuuban:",
  "Qiimo dhimis%:",
  "Ku dar badeecada",
  "Faahfaahin dalbo",
  "Faahfaahinta dhoofinta",
  "Dalbashada id:",
  "Dalabka",
  "ordaya(@number)",
  "la keenay (@number)",
  "la codsaday (@number)",
  "Gaadhista oo socota",
  "Qadarka (@number)",
  "Wax ka beddel astaanta",
  "Lambarka taleefanka",
  "Magaca buuxa",
  "Cinwaanka",
  "Shandadayda",
  "Hadhaaga boorsada",
  "Miles dheelitirka",
  "@number mayl",
  "Taariikhda wax kala iibsiga",
  "Ku sifee taariikhda",
  "Ku shubida boorsada",
  "Ogeysiisyada",
  "Maanta",
  "Ogeysiinta nidaamka",
  "Wax ka beddel",
  "Qiimaynta",
  "Daba gal",
  "raacayaal",
  "Alaabtayda",
  "Shandadayda",
  "Menu",
  "Beddel luqadda",
  "Dejinta",
  "Xarunta taageerada",
  "Shuruudaha & Shuruudaha",
  "tixraac",
  "Dejinta",
  "Bogga hore ee asalka ah",
  "Raad app",
  "Bogga ganacsiga e-commerce",
  "gaarsiin cunto",
  "Mawduuca midabka",
  "Iftiin",
  "Madow",
  "Daar kanaalada isgaarsiinta",
  "Dejinta xisaabta",
  "Ka bax",
  "Tirtir xisaabta",
  "Guriga",
  "Dalabka",
  "Daawo",
  "Aniga",
  "Makhaayadaha Dhow",
  "Dalabka cusub",
  "Ku dar dhimis",
  "Qiimo dhimis",
  "Qiimo dhimis (ikhtiyaar)",
  "Ku dar kuuban",
  "Dooro nooca xoojinta",
  "Soo rar sawirka banner",
  "Dalag sawirka banner",
];

// const values6 = [
//   "The rate you selected is already sold out. Try a different search than the flexible calendar.",
//   "Stato attuale",
//   "Chat dal vivo",
//   "Vuoi chattare con i nostri agenti?",
//   "Chatta con gli agenti",
// ];

// const values7 = [
//   "La tarifa que seleccionaste ya está agotada. Intente una búsqueda diferente desde el calendario flexible.",
//   "Estado actual",
//   "Chat en vivo",
//   "Quieres chatear con nuestros agentes?",
//   "Chatea con agentes",
// ];

// const values8 = [
//   "እቲ ዝመረጽካዮ ክፍሊት ተሸይጡ። በጃኹም ኣብ ታሕቲ ዘሎ ናይ ክፍሊት ምርኢት ተጠቒምኩም ሓድሽ በረራ ምረጹ።",
//   "አሁን ያለበት ሁኔታ",
//   "ላይቭ ቻት",
//   "ወኪል ማነጋገር ይፍለጋሉ?",
//   "ምስ ሓደ ወኪል ተዘራረብ",
// ];

// const values9 = [
//   "A tarifa que você selecionou já está esgotada. Por favor, tente uma pesquisa diferente do calendário flexível.",
//   "Status atual",
//   "Bate-papo ao vivo",
//   "Quer conversar com nossos agentes?",
//   "Converse com agentes",
// ];

// const values10 = [
//   "選択した運賃はすでに完売しています。フレキシブルカレンダーから別の検索をお試しください。",
//   "現在のステータス",
//   "ライブチャット",
//   "弊社のエージェントとチャットしたいですか?",
//   "エージェントとのチャット",
// ];

// const values11 = [
//   "Tikidhka aad dooratay mar hore waa la iibiyay. Fadlan isku day raadinta ka duwan kalandarka dabacsan.",
//   "Xaalada hadda",
//   "Sheeko toos ah",
//   "Ma rabtaa inaad la hadasho wakiiladayada?",
//   "Kala hadal Wakiilada",
// ];

// const values12 = [
//   "ค่าโดยสารที่คุณเลือกได้จำหน่ายหมดแล้ว โปรดลองค้นหาอื่นจากปฏิทินแบบยืดหยุ่น",
//   "สถานะปัจจุบัน",
//   "แชทสด",
//   "คุณต้องการพูดคุยกับตัวแทนของเราหรือไม่?",
//   "พูดคุยกับตัวแทน",
// ];

// const values13 = [
//   "선택하신 요금은 이미 매진되었습니다. 가변캘린더에서 다른 검색을 시도해 보세요.",
//   "현재 상태",
//   "실시간 채팅",
//   "우리 상담원과 채팅하고 싶으신가요?",
//   "상담원과 채팅",
// ];

// const values14 = [
//   "Выбранный вами тариф уже распродан. Попробуйте другой поиск в гибком календаре.",
//   "Текущее состояние",
//   "Живой чат",
//   "Хотите пообщаться с нашими агентами?",
//   "Чат с агентами",
// ];

console.log("EN");

printMapInFormat(mergeToList(keys, values1));

console.log("AM");

printMapInFormat(mergeToList(keys, values2));

console.log("TI");

printMapInFormat(mergeToList(keys, values3));

console.log("OM");

printMapInFormat(mergeToList(keys, values4));

console.log("SO");

printMapInFormat(mergeToList(keys, values5));

// console.log("it");

// printMapInFormat(mergeToList(keys, values6));

// console.log("es_ES");

// printMapInFormat(mergeToList(keys, values7));

// console.log("ti");

// printMapInFormat(mergeToList(keys, values8));

// console.log("pt_PT");

// printMapInFormat(mergeToList(keys, values9));

// console.log("ja");

// printMapInFormat(mergeToList(keys, values10));

// console.log("so");

// printMapInFormat(mergeToList(keys, values11));

// console.log("so");

// printMapInFormat(mergeToList(keys, values12));

// console.log("ko");

// printMapInFormat(mergeToList(keys, values13));

// console.log("ru");

// printMapInFormat(mergeToList(keys, values14));
